<%@ Page Title="" Language="C#" MasterPageFile="~/admin/AdminMP.master" AutoEventWireup="true" CodeFile="ManagerOrders.aspx.cs" Inherits="admin_ManagerOrders" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <style type="text/css">
        .style9
        {
            width: 229px;
        }
        .style10
        {
            width: 229px;
            height: 19px;
        }
        .style15
        {
            width: 21px;
        }
        .style18
        {
            width: 68px;
        }
        .style17
        {
            width: 38px;
        }
        </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <table style="width: 100%; height: 401px;">
        <tr>
            <td class="style10">
            </td>
            <td rowspan="3" style="vertical-align: top; text-align: left">
                <asp:GridView ID="GridView1" runat="server" AllowPaging="True" 
                    AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" 
                    DataKeyNames="订单ID" ForeColor="#333333" GridLines="None" Height="16px" 
                    onpageindexchanging="GridView1_PageIndexChanging" 
                    onrowcancelingedit="GridView1_RowCancelingEdit" 
                    onrowcommand="GridView1_RowCommand" onrowediting="GridView1_RowEditing" 
                    onrowupdating="GridView1_RowUpdating" Width="633px">
                    <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                    <Columns>
                        <asp:ButtonField CommandName="send" Text="开始发货" />
                    </Columns>
                    <EditRowStyle BackColor="#999999" />
                    <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                    <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                    <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                    <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                    <SortedAscendingCellStyle BackColor="#E9E7E2" />
                    <SortedAscendingHeaderStyle BackColor="#506C8C" />
                    <SortedDescendingCellStyle BackColor="#FFFDF8" />
                    <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
                </asp:GridView>
            </td>
        </tr>
        <tr>
            <td class="style9" style="vertical-align: top">
            <table style="width: 97%; height: 150px;">
                <tr>
                    <td class="style15">
                        &nbsp;</td>
                    <td class="style18">
                        <asp:LinkButton ID="LBtnUserManager" runat="server" Font-Bold="True" 
                                Font-Size="Small" onclick="LBtnUserManager_Click">用户管理</asp:LinkButton>
                    </td>
                    <td class="style17">
                        &nbsp;</td>
                </tr>
                <tr>
                    <td class="style15">
                        &nbsp;</td>
                    <td class="style18">
                        <asp:LinkButton ID="LBtnFoodManager" runat="server" Font-Bold="True" 
                                Font-Size="Small" onclick="LBtnFoodManager_Click">菜品管理</asp:LinkButton>
                    </td>
                    <td class="style17">
                        &nbsp;</td>
                </tr>
                <tr>
                    <td class="style15">
                        &nbsp;</td>
                    <td class="style18">
                        <asp:LinkButton ID="LinkButton3" runat="server" Font-Bold="True" 
                                Font-Size="Small" onclick="LinkButton3_Click">订单管理</asp:LinkButton>
                    </td>
                    <td class="style17">
                        &nbsp;</td>
                </tr>
                <tr>
                    <td class="style15">
                        &nbsp;</td>
                    <td class="style18">
                        <asp:LinkButton ID="LinkButton4" runat="server" Font-Bold="True" 
                                Font-Size="Small" onclick="LinkButton4_Click">销售统计</asp:LinkButton>
                    </td>
                    <td class="style17">
                        &nbsp;</td>
                </tr>
            </table>
            </td>
        </tr>
        <tr>
            <td class="style9">
                &nbsp;</td>
        </tr>
    </table>
</asp:Content>

