<%@ Page Title="" Language="C#" MasterPageFile="~/admin/AdminMP.master" AutoEventWireup="true" CodeFile="ManagerUsers.aspx.cs" Inherits="admin_ManagerUsers" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <style type="text/css">

        .style10
        {
            width: 176px;
            height: 4px;
        }
        .style12
        {
            width: 176px;
            height: 303px;
        }
        .style15
        {
            width: 21px;
        }
        .style18
        {
            width: 68px;
        }
        .style17
        {
            width: 38px;
        }
        .style19
    {
        width: 176px;
    }
    .style20
    {
        width: 766px;
    }
</style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <table style="width: 100%; height: 434px;">
    <tr>
        <td class="style10">
        </td>
        <td class="style20" rowspan="3" style="vertical-align: top; text-align: left">
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <br />
            <asp:GridView ID="GridView2" runat="server" AutoGenerateDeleteButton="True" 
                AutoGenerateEditButton="True" CellPadding="4" DataKeyNames="userID" 
                ForeColor="#333333" GridLines="None" Height="170px" 
                onrowcancelingedit="GridView2_RowCancelingEdit" 
                onrowediting="GridView2_RowEditing" onrowupdating="GridView2_RowUpdating" 
                Width="733px" onrowcommand="GridView2_RowCommand" 
                onrowdeleting="GridView2_RowDeleting" AllowPaging="True" 
                onpageindexchanging="GridView2_PageIndexChanging">
                <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                <Columns>
                    <asp:ButtonField Text="新增" CommandName="addUser" />
                </Columns>
                <EditRowStyle BackColor="#999999" />
                <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#E9E7E2" />
                <SortedAscendingHeaderStyle BackColor="#506C8C" />
                <SortedDescendingCellStyle BackColor="#FFFDF8" />
                <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
            </asp:GridView>
        </td>
    </tr>
    <tr>
        <td class="style12" style="vertical-align: top">
            <table style="width: 97%; height: 150px;">
                <tr>
                    <td class="style15">
                        &nbsp;</td>
                    <td class="style18">
                        <asp:LinkButton ID="LBtnUserManager" runat="server" Font-Bold="True" 
                                Font-Size="Small" onclick="LBtnUserManager_Click">用户管理</asp:LinkButton>
                    </td>
                    <td class="style17">
                        &nbsp;</td>
                </tr>
                <tr>
                    <td class="style15">
                        &nbsp;</td>
                    <td class="style18">
                        <asp:LinkButton ID="LBtnFoodManager" runat="server" Font-Bold="True" 
                                Font-Size="Small" onclick="LBtnFoodManager_Click">菜品管理</asp:LinkButton>
                    </td>
                    <td class="style17">
                        &nbsp;</td>
                </tr>
                <tr>
                    <td class="style15">
                        &nbsp;</td>
                    <td class="style18">
                        <asp:LinkButton ID="LinkButton3" runat="server" Font-Bold="True" 
                                Font-Size="Small" onclick="LinkButton3_Click">订单管理</asp:LinkButton>
                    </td>
                    <td class="style17">
                        &nbsp;</td>
                </tr>
                <tr>
                    <td class="style15">
                        &nbsp;</td>
                    <td class="style18">
                        <asp:LinkButton ID="LinkButton4" runat="server" Font-Bold="True" 
                                Font-Size="Small" onclick="LinkButton4_Click">销售统计</asp:LinkButton>
                    </td>
                    <td class="style17">
                        &nbsp;</td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td class="style19">
            &nbsp;</td>
    </tr>
</table>
</asp:Content>

